apiBaseUrl=http://localhost:4111
apiVersion=/api/v1

adminLogin=admin
adminPassword=admin

uiRemote=http://localhost:4444/wd/hub
uiBaseUrl=http://192.168.1.182:3000
uiBrowser=chrome
uiBrowserSize=1920x1080

test.retry.maxAttempts=3
test.retry.delayMs=1000