
### Positive test: Authorized user can see their accounts
POST http://localhost:4111/api/v1/customer/accounts
Content-Type: application/json
Authorization: Basic S2F0ZTE5OTcuOkthdGUxOTk3QA==

### Positive test: Authorized user can deposit up his account
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic S2F0ZTE5OTcuOkthdGUxOTk3QA==

{
  "id": 2,
  "balance": 5000
}

### Positive test boundary: Authorized user can deposit up his account minimum allowed amount (0.01)
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic S2F0ZTE5OTcuOkthdGUxOTk3QA==

{
  "id": 2,
  "balance": 0.01
}


### Positive test boundary: Authorized user can deposit up his account max 5000
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic S2F0ZTE5OTcuOkthdGUxOTk3QA==

{
  "id": 2,
  "balance": 4999.99
}

### Negative test boundary: Authorized user can maximum deposit 5000, check 5000.01 (code200 bug)
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic S2F0ZTE5OTcuOkthdGUxOTk3QA==

{
  "id": 2,
  "balance": 5000.01
}

### Negative test: Authorized user can deposit a positive amount
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic S2F0ZTE5OTcuOkthdGUxOTk3QA==

{
  "id": 2,
  "balance": -100
}

### Negative test: Authorized user cannot make deposit to non-existent account
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic S2F0ZTE5OTcuOkthdGUxOTk3QA==

{
  "id": 5,
  "balance": 100
}

### Negative test: Authorized user cannot make deposit into someone else's account
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic S2F0ZTE5OTcuOkthdGUxOTk3QA==

{
  "id": 1,
  "balance": 100
}

### Positive test: Check money has been deposite(user can see the transactions of their accounts)
GET http://localhost:4111/api/v1/accounts/2/transactions
Content-Type: application/json
Authorization: Basic S2F0ZTE5OTcuOkthdGUxOTk3QA==

### Positive test: Authorized user can transfer money from one account to another
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic S2F0ZTE5OTcuOkthdGUxOTk3QA==

{
  "senderAccountId": 2,
  "receiverAccountId": 1,
  "amount": 1000
}

### Negative test boundary: Authorized user cannot transfer amount greater than max limit 10000 (code 200 bug)
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic S2F0ZTE5OTcuOkthdGUxOTk3QA==

{
  "senderAccountId": 2,
  "receiverAccountId": 3,
  "amount": 10000.01
}

### Positive test boundary: Authorized user can transfer money max 10000, check 9999.99
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic S2F0ZTE5OTcuOkthdGUxOTk3QA==

{
  "senderAccountId": 2,
  "receiverAccountId": 3,
  "amount": 9999.99
}

### Positive test boundary: Authorized user can transfer minimum allowed amount (0.01)
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic S2F0ZTE5OTcuOkthdGUxOTk3QA==

{
  "senderAccountId": 2,
  "receiverAccountId": 3,
  "amount": 0.01
}


### Negative test: Authorized user can transfer only positive amount
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic S2F0ZTE5OTcuOkthdGUxOTk3QA==

{
  "senderAccountId": 2,
  "receiverAccountId": 3,
  "amount": -10
}

### Negative test: Authorized user can transfer amount not exceeding the balance
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic S2F0ZTE5OTguOkthdGUxOTk4QA==

{
  "senderAccountId": 1,
  "receiverAccountId": 3,
  "amount": 10000
}

### Positive test: Authorized user can update name in profile
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic S2F0ZTE5OTguOkthdGUxOTk4QA==

{
  "name": "New Name"
}

### Negative test: Name must consist of two words separated by a space(200)
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic S2F0ZTE5OTguOkthdGUxOTk4QA==

{
  "name": "NewName"
}

### Negative test: Name must contain only letters(200)
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic S2F0ZTE5OTguOkthdGUxOTk4QA==

{
  "name": "New 111"
}